openapi: 3.0.1
info:
  title: ContextGPT API
  description: API para gerenciar contexto de arquivos e gerar respostas com contexto.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/  # Ajuste para o seu endereço e porta
paths:
  /context/{file_path}:
    get:
      summary: Recupera o embedding de um arquivo.
      parameters:
        - name: file_path
          in: path
          description: Caminho do arquivo.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Embedding do arquivo encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  content:
                    type: array
                    items:
                      type: number
        '404':
          description: Arquivo não encontrado.
    delete:
      summary: Remove o contexto de um arquivo específico.
      parameters:
        - name: file_path
          in: path
          description: Caminho do arquivo.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contexto removido com sucesso.
        '404':
          description: Arquivo não encontrado.
  /generate-response:
    post:
      summary: Gera uma resposta com base no contexto dos arquivos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: O prompt de entrada para gerar a resposta.
      responses:
        '200':
          description: Resposta gerada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  response:
                    type: string
                    description: A resposta gerada pelo modelo.
        '400':
          description: Requisição inválida.
        '500':
          description: Erro interno do servidor.
  /health:
    get:
      summary: Verifica a saúde da aplicação.
      responses:
        '200':
          description: Aplicação saudável.
        '500':
          description: Aplicação com problemas.
