openapi: 3.0.0
info:
  title: ContextGPT API
  description: API para gerenciar contexto de arquivos e gerar respostas usando GPT-4.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Servidor local

paths:
  /context:
    post:
      summary: Atualiza o contexto dos arquivos
      description: Verifica se a entrada é JSON válida e atualiza o dicionário de contexto com o conteúdo do arquivo fornecido.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  example: "caminho/do/arquivo.py"
                content:
                  type: string
                  example: "Conteúdo do arquivo."
      responses:
        '200':
          description: Context updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Context updated."
        '400':
          description: Invalid input, JSON expected
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Invalid input, JSON expected."

  /context/{file_path}:
    get:
      summary: Recupera o contexto de um arquivo específico
      parameters:
        - name: file_path
          in: path
          required: true
          schema:
            type: string
            example: "caminho/do/arquivo.py"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  content:
                    type: string
                    example: "Conteúdo do arquivo."
        '404':
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "File not found."

    delete:
      summary: Remove o contexto de um arquivo específico
      parameters:
        - name: file_path
          in: path
          required: true
          schema:
            type: string
            example: "caminho/do/arquivo.py"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Context removed."
        '404':
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "File not found."

  /generate-response:
    post:
      summary: Gera uma resposta usando o modelo GPT-4
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: "Explique o que faz este trecho de código."
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  response:
                    type: string
                    example: "Este trecho de código faz XYZ."
        '400':
          description: Prompt is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Prompt is required."
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Internal server error."

  /health:
    get:
      summary: Verifica o status de saúde da aplicação
      responses:
        '200':
          description: Application is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Application is healthy."
        '500':
          description: Application is unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Application is unhealthy."

  /metrics:
    get:
      summary: Exibe as métricas de performance da aplicação
      responses:
        '200':
          description: Métricas geradas pelo Prometheus
